#ifndef UI_THEME_H
#define UI_THEME_H

/* Shared UI layout/tuning constants. */
#define UI_BOARD_SCALE_PERCENT 78
#define UI_BOARD_MIN_GAP 6

#define UI_TUTORIAL_TITLE_Y 30
#define UI_TUTORIAL_TITLE_SCALE_MOVE 4
#define UI_TUTORIAL_TITLE_SCALE_MERGE 3
#define UI_TUTORIAL_TITLE_SCALE_GOAL 3

#define UI_TUTORIAL_ARROW_HEAD_WIDTH 24
#define UI_TUTORIAL_ARROW_MIN_W 24
#define UI_TUTORIAL_ARROW_MIN_H 12

#define UI_HUD_TITLE_X 24
#define UI_HUD_TITLE_Y 20
#define UI_HUD_SCORE_BOX_X 24
#define UI_HUD_SCORE_BOX_Y 84
#define UI_HUD_SCORE_BOX_W 220
#define UI_HUD_SCORE_BOX_H 74
#define UI_HUD_SCORE_VALUE_SCALE 4

#endif
