#ifndef UI_THEME_H
#define UI_THEME_H

#include "ui/ui_context.h"

/* Shared UI layout/tuning constants. */
#define UI_BOARD_SCALE_PERCENT 78
#define UI_BOARD_MIN_GAP 6

#define UI_TUTORIAL_TITLE_Y 30
#define UI_TUTORIAL_TITLE_SCALE_MOVE 4
#define UI_TUTORIAL_TITLE_SCALE_MERGE 3
#define UI_TUTORIAL_TITLE_SCALE_GOAL 3

#define UI_TUTORIAL_ARROW_HEAD_WIDTH 24
#define UI_TUTORIAL_ARROW_MIN_W 24
#define UI_TUTORIAL_ARROW_MIN_H 12
#define UI_TUTORIAL_ARROW_INNER_INSET 2
#define UI_TUTORIAL_MOVE_ARROW_MIN_H 18
#define UI_TUTORIAL_MOVE_ARROW_START_PAD 8
#define UI_TUTORIAL_MERGE_ARROW_MIN_H 12
#define UI_TUTORIAL_MERGE_ARROW_MIN_W 64
#define UI_TUTORIAL_MERGE_ARROW_X_OFFSET 104
#define UI_TUTORIAL_MERGE_ARROW_Y_OFFSET 32

#define UI_TUTORIAL_FOOTER_SCALE 3
#define UI_TUTORIAL_FOOTER_Y_OFFSET 52

#define UI_HUD_TITLE_X 24
#define UI_HUD_TITLE_Y 20
#define UI_HUD_SCORE_BOX_X 24
#define UI_HUD_SCORE_BOX_Y 84
#define UI_HUD_SCORE_BOX_W 220
#define UI_HUD_SCORE_BOX_H 74
#define UI_HUD_SCORE_VALUE_SCALE 4

#define UI_COLOR_BG ui_rgb(248, 246, 240)
#define UI_COLOR_BOARD ui_rgb(187, 173, 160)
#define UI_COLOR_TILE_BLOCKED ui_rgb(236, 196, 74)
#define UI_COLOR_TEXT_DARK ui_rgb(90, 80, 70)
#define UI_COLOR_TEXT_TILE_DARK ui_rgb(100, 95, 90)
#define UI_COLOR_TEXT_TITLE ui_rgb(120, 110, 101)
#define UI_COLOR_TEXT_SUBTLE ui_rgb(150, 138, 128)
#define UI_COLOR_TEXT_LIGHT ui_rgb(248, 246, 242)
#define UI_COLOR_TEXT_ACCENT ui_rgb(240, 170, 20)
#define UI_COLOR_TEXT_SCORE_LABEL ui_rgb(238, 228, 218)
#define UI_COLOR_WIN ui_rgb(237, 194, 46)
#define UI_COLOR_ARROW_FILL ui_rgb(235, 170, 10)
#define UI_COLOR_ARROW_OUTLINE ui_rgb(162, 122, 16)
#define UI_COLOR_OVERLAY_DARK ui_rgb(120, 90, 80)
#define UI_COLOR_OVERLAY_MID ui_rgb(145, 104, 90)
#define UI_COLOR_OVERLAY_TEXT ui_rgb(255, 246, 235)
#define UI_COLOR_OVERLAY_TEXT_SOFT ui_rgb(255, 232, 208)

#endif
